/**
 * Brand Kit — runtime data fetcher (auto-generated by Tyashin)
 *
 * Fetches brand kit data (logos, colors, fonts, site name) from the Tyashin
 * backend at request time with ISR caching (5-minute revalidation).
 *
 * When the admin changes the brand kit in Tyashin, the website automatically
 * picks up the new values within 5 minutes — no rebuild or regeneration needed.
 */

export interface BrandKitData {
  version: number;
  siteName: string;
  logo?: {
    light?: string;
    dark?: string;
    monogram?: string;
    favicon?: string;
    aspectRatio?: string;
  };
  colors?: {
    primary: string;
    primaryContrast: string;
    accent?: string;
    background: string;
    surface: string;
    text: string;
    textMuted: string;
    border: string;
  };
  typography?: {
    headingFont?: string;
    bodyFont?: string;
  };
  radius?: {
    sm: string;
    md: string;
    lg: string;
    full: string;
  };
}

const BRAND_KIT_URL = 'https://website-api.tyashin.com/api/v1/public/brand-kit.json?projectId=69f1354e7766b41fbc101ded';

/**
 * Fetch brand kit data from the Tyashin backend.
 * Uses Next.js ISR with 5-minute revalidation for optimal performance.
 */
export async function getBrandKit(): Promise<BrandKitData> {
  try {
    const res = await fetch(BRAND_KIT_URL, {
      next: { revalidate: 300 },
    });
    if (res.ok) {
      return (await res.json()) as BrandKitData;
    }
  } catch {
    // Fetch failed — return fallback
  }

  return {
    version: 0,
    siteName: 'Thridify',
  };
}
