/**
 * Brand Kit — runtime data fetcher (auto-generated by Tyashin)
 *
 * Fetches brand kit data (logos, colors, fonts, site name) from the Tyashin
 * backend at request time with ISR caching (5-minute revalidation).
 *
 * When the admin changes the brand kit in Tyashin, the website automatically
 * picks up the new values within 5 minutes — no rebuild or regeneration needed.
 *
 * Usage in Server Components:
 *   import { getBrandKit } from '@/lib/brand-kit';
 *   const brandKit = await getBrandKit();
 *   // brandKit.logo?.light — logo URL for light backgrounds
 *   // brandKit.siteName — project name
 */

export interface BrandKitData {
  version: number;
  siteName: string;
  logo?: {
    light?: string;
    dark?: string;
    monogram?: string;
    favicon?: string;
    aspectRatio?: string;
  };
  colors?: {
    primary: string;
    primaryContrast: string;
    accent?: string;
    background: string;
    surface: string;
    text: string;
    textMuted: string;
    border: string;
    success?: string;
    warning?: string;
    danger?: string;
  };
  typography?: {
    headingFont?: string;
    bodyFont?: string;
  };
  radius?: {
    sm: string;
    md: string;
    lg: string;
    full: string;
  };
}

const BRAND_KIT_URL = 'https://website-api.tyashin.com/api/v1/public/brand-kit.json?apiKey=ak_MHWfta1xNEEMAmI1UbSE99HEwTuAEWix';

let cachedBrandKit: BrandKitData | null = null;

/**
 * Fetch brand kit data from the Tyashin backend.
 * Uses Next.js ISR with 5-minute revalidation for optimal performance.
 *
 * Returns a default fallback if the fetch fails (site still renders).
 */
export async function getBrandKit(): Promise<BrandKitData> {
  if (cachedBrandKit) return cachedBrandKit;

  try {
    const res = await fetch(BRAND_KIT_URL, {
      next: { revalidate: 300 }, // Re-fetch every 5 minutes
    });
    if (res.ok) {
      const data = await res.json();
      cachedBrandKit = data as BrandKitData;
      return cachedBrandKit;
    }
  } catch {
    // Fetch failed — return fallback (site still works with CSS variable defaults)
  }

  return {
    version: 0,
    siteName: '',
  };
}
