import type { Metadata, Viewport } from 'next';
import { bodyFont, headingFont, monoFont } from '@/lib/fonts';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { ScrollFX } from '@/components/motion/ScrollFX';
import { PointerFX } from '@/components/motion/PointerFX';
import { MobileCtaBar } from '@/components/MobileCtaBar';
import { ScrollToTop } from '@/components/ScrollToTop';
import { PrintFX } from '@/components/PrintFX';
import { EntitySchema } from '@/components/SiteSchema';
import './globals.css';

// Absolute base for OG/Twitter URLs. While previewed on workers.dev this
// must point at the preview host so OG images actually resolve; on the
// Phase 7 cutover set SITE_URL=https://thridify.com (or www per the
// canonical-host decision) in the deploy environment.
const SITE_URL =
  process.env.SITE_URL ?? 'https://thridify.com';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'Thridify — Reimagine how the world experiences your products',
    template: '%s | Thridify',
  },
  description:
    'Thridify is a no-code 3D and Augmented Reality commerce platform that helps e-commerce brands boost conversions, reduce returns, and cut photography costs.',
  keywords: ['3D commerce', 'AR commerce', 'product configurator', '3D viewer', 'augmented reality e-commerce', 'Thridify', 'Aapastech'],
  openGraph: {
    title: 'Thridify — 3D & AR Commerce Platform',
    description: 'No-code 3D and AR product experiences that boost e-commerce conversions.',
    type: 'website',
    siteName: 'Thridify',
    // Brand-colored generated static (scripts/generate-og.mjs) — real
    // product-render OG images are tracked in docs/ASSET-DEBT.md.
    images: ['/og/default.png'],
  },
  twitter: {
    card: 'summary_large_image',
  },
  icons: {
    // Scheme-aware tab icons: the teal layer of the mark is only 2.8:1 on a
    // dark tab strip, so the dark variant lifts it to primary-soft
    // (public/brand/favicon-dark.png, generated by scripts/generate-favicons.mjs).
    icon: [
      { url: '/brand/favicon-light.png', media: '(prefers-color-scheme: light)', type: 'image/png' },
      { url: '/brand/favicon-dark.png', media: '(prefers-color-scheme: dark)', type: 'image/png' },
      { url: '/brand/logo-favicon.png', type: 'image/png' },
    ],
    apple: '/brand/apple-touch-icon.png',
  },
};

// Browser chrome follows the scheme (address bar / tab strip on mobile).
export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#FFFFFF' },
    { media: '(prefers-color-scheme: dark)', color: '#021F17' },
  ],
};

/**
 * Canonical brand tokens per DESIGN-SPEC §1/§2 — non-negotiable, and the
 * ONLY brand-token source this app loads.
 *
 * Why there is deliberately NO <link> to the platform's
 * website-api.tyashin.com/.../brand-kit.css here:
 *  1. It was render-blocking and cost 3.0–3.5s TTFB on a cold platform edge
 *     (Atlas cold-connect) — it single-handedly pushed FCP/LCP past 5s and
 *     Lighthouse-mobile perf to ~64 on every page.
 *  2. This inline block re-declares every --brand-* variable the app uses,
 *     so the external sheet contributed nothing (it currently serves a STALE
 *     pre-canonical palette anyway — ASSET-DEBT #13).
 *  3. Loading it async instead would flip the cascade order (appended last →
 *     stale values would beat these canonical ones). Not worth the hazard.
 * On custom domains (Phase 7) the platform edge can inject brand-kit.css
 * itself; once the kit is PATCHed to these exact values the two sources
 * agree by construction.
 *
 * DARK SCHEME: this block is the LIGHT palette only. The dark values live
 * once, in globals.css, under `:root:not([data-theme="light"])` (0,2,0) —
 * more specific than this block, so they win regardless of source order.
 * Do not add dark values here.
 *
 * SELECTOR: `html:root` (0,1,1), not `:root` (0,1,0). The platform edge on
 * *.sites.tyashin.com injects its own `<style id="brand-kit">:root{…}` AFTER
 * this block (verified live 2026-09-10: it carried a stale default palette —
 * --brand-primary #111827 and system fonts — which turned every light-mode
 * button navy and dropped Space Grotesk/Inter in production). With (0,1,1)
 * the canonical palette beats any injected plain `:root` by specificity,
 * whatever the order; the dark block (0,2,0) still beats both.
 */
const CANONICAL_BRAND_CSS = `
/* First-frame paint (addendum §11): html/body take the page ground from the
   very first frame, before the CSS bundle arrives — scheme-aware, so a dark-
   mode visitor never sees a white flash. Only --brand-bg is mirrored here;
   the full dark palette lives in globals.css. */
html, body { background-color: var(--brand-bg); }
@media (prefers-color-scheme: dark) {
  html:root:not([data-theme="light"]) { --brand-bg: #021F17; }
}
html:root[data-theme="dark"] { --brand-bg: #021F17; }
html:root {
  --brand-primary: #007050;
  --brand-primary-deep: #004D37;
  --brand-primary-contrast: #FFFFFF;
  --brand-accent: #FEBFCC;
  --brand-ink: #021F17;
  --brand-bg: #FFFFFF;
  --brand-paper: #FFFFFF;
  --brand-surface: #F0F5FA;
  --brand-text: #021F17;
  --brand-text-muted: #5B7A6E;
  --brand-muted-dark: #A3BFB5;
  --brand-primary-soft: #6FCFAB;
  --brand-border: rgba(2, 31, 23, 0.08);
  --brand-radius-sm: 0.5rem;
  --brand-radius-md: 0.75rem;
  --brand-radius-lg: 1rem;
  --brand-radius-full: 999px;
  --brand-heading-font: var(--font-heading), 'Space Grotesk', sans-serif;
  --brand-body-font: var(--font-body), 'Inter', sans-serif;
  --brand-mono-font: var(--font-mono), 'IBM Plex Mono', monospace;
}
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${bodyFont.variable} ${headingFont.variable} ${monoFont.variable}`}>
      <head>
        {/* Canonical palette — single token source (see CANONICAL_BRAND_CSS note). */}
        <style dangerouslySetInnerHTML={{ __html: CANONICAL_BRAND_CSS }} />
        {/* Warm the 3D runtime origins before the client requests them:
            mviewer.js is a classic <script> (no-CORS → no crossorigin here);
            models.thridify.com is fetched with CORS (crossorigin required or
            the warmed socket can't be reused). */}
        <link rel="preconnect" href="https://viewer.thridify.com" />
        <link rel="preconnect" href="https://models.thridify.com" crossOrigin="anonymous" />
      </head>
      <body className="font-body bg-background text-foreground antialiased">
        {/* Skip-to-content link (WCAG 2.4.1) — visually hidden until focused,
            then a visible pink-ringed pill at the top-left. */}
        <a href="#main-content" className="skip-link">
          Skip to content
        </a>
        {/* Reading-progress hairline (luxury pass) — scroll-driven pure CSS,
            renders nothing on engines without animation-timeline. */}
        <div className="scroll-progress" aria-hidden />

        {/* Sitewide entity graph: Organization + SoftwareApplication on every
            page (per-page Service/FAQ/Breadcrumb blocks live in their pages). */}
        <EntitySchema />
        {/* ─────────────────────────────────────────────────────────────
            COOKIE / CONSENT INTEGRATION POINT (Phase 4, CHUNK 3).
            This site is consent-READY but deliberately ships NO bespoke
            cookie banner. Rationale:
              1. Today the site sets only strictly-necessary cookies
                 (Cloudflare security) and wires NO analytics/ad trackers, so
                 nothing non-essential runs pre-consent — nothing to gate yet.
              2. The consent banner + non-essential-cookie gating is owned by
                 the platform **consent-manager PLUGIN** (not yet installed;
                 needs a JWT, orchestrator-tracked — see docs/ASSET-DEBT.md
                 #23). A hand-rolled banner here would COLLIDE with the plugin
                 at install. When analytics is enabled it must be mounted
                 THROUGH the plugin's consent gate, not directly.
            Mount the plugin's consent script here at install time; do not add
            a custom banner. ───────────────────────────────────────────── */}
        <Header />
        {/* overflow-x-clip (addendum §11): contains decorative glows / marquees
            without creating a scroll container, so sticky sections still work. */}
        <main id="main-content" tabIndex={-1} className="min-h-screen overflow-x-clip">
          {children}
        </main>
        <Footer />
        {/* §9 law: sticky mobile Book-a-Demo bar after 50% scroll. */}
        <MobileCtaBar />
        {/* Back-to-top ring (luxury pass) + print-time FAQ expansion. */}
        <ScrollToTop />
        <PrintFX />
        {/* Sitewide declarative scroll effects (data-parallax / data-fx) —
            wires GSAP ScrollTriggers to server-rendered markup. */}
        <ScrollFX />
        {/* Cursor-aware micro-physics: card spotlight + magnetic primary CTAs
            (fine pointers only). */}
        <PointerFX />
      </body>
    </html>
  );
}
